version: '3.8'

services:
  focusider-fe:
    image: mango0422/focusider-fe:latest
    container_name: my-app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: always
