import type { Metadata } from 'next';
import { Gowun_Dodum, Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import PageContainer from '@/app/_components/layout/PageContainer';

const notoSansKR = Noto_Sans_KR({ subsets: ['latin'] });
const gowunDodum = Gowun_Dodum({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--gowun',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${notoSansKR.className} ${gowunDodum.variable}`}>
      <body>
        <PageContainer>{children}</PageContainer>
      </body>
    </html>
  );
}
